from fastapi import FastAPI, Depends, HTTPException, Header
from sqlalchemy.orm import Session
from sqlalchemy import func
from . import models, schemas
from .database import engine, get_db

# This creates the database tables when the app starts
models.Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="Finance Dashboard API",
    description="Backend for managing financial records and user roles.",
    version="1.0.0"
)


# def require_role(allowed_roles: list[str]):
#     def role_checker(x_user_id: int = Header(..., description="Simulates the logged-in user ID"), db: Session = Depends(get_db)):
#         # 1. Find the user making the request
#         user = db.query(models.User).filter(
#             models.User.id == x_user_id).first()

#         if not user:
#             raise HTTPException(
#                 status_code=401, detail="User not authenticated")

#         # 2. Check if their role is in the allowed list
#         if user.role not in allowed_roles:
#             raise HTTPException(
#                 status_code=403, detail="You do not have permission to do this!")

#         # 3. If they pass, let them in!
#         return user

#     return role_checker


# @app.post("/users", response_model=schemas.UserResponse)
# def create_user(user: schemas.UserCreate, db: Session = Depends(get_db)):
#     # 1. Check if the email is already in the database
#     db_user = db.query(models.User).filter(
#         models.User.email == user.email).first()
#     if db_user:
#         raise HTTPException(status_code=400, detail="Email already registered")

#     # 2. Create the Database Object
#     # (Note: We are storing the password as plain text just for this step.
#     # We will add hashing later to make it secure!)
#     new_user = models.User(
#         email=user.email,
#         password=user.password,
#         role=user.role
#     )

#     # 3. Add to Database and Save
#     db.add(new_user)
#     db.commit()
#     db.refresh(new_user)  # Grabs the new ID generated by SQLite

#     # 4. Return the user
#     # (FastAPI automatically pushes this through the UserResponse schema to hide the password)
#     return new_user


# # 1. ONLY Admins can create records!
# @app.post("/records", response_model=schemas.RecordResponse)
# def create_record(
#     record: schemas.RecordCreate,
#     db: Session = Depends(get_db),
#     current_user: models.User = Depends(
#         require_role(["ADMIN"]))  # <-- SECURITY CHECK
# ):
#     new_record = models.Record(
#         amount=record.amount,
#         type=record.type,
#         category=record.category,
#         date=record.date,
#         notes=record.notes,
#         user_id=current_user.id  # We get the ID securely from the logged-in user now!
#     )
#     db.add(new_record)
#     db.commit()
#     db.refresh(new_record)
#     return new_record


# @app.get("/records", response_model=list[schemas.RecordResponse])
# def get_all_records(
#     skip: int = 0,
#     limit: int = 100,
#     transaction_type: str = None,
#     db: Session = Depends(get_db)
# ):
#     # Start a query
#     query = db.query(models.Record)

#     # Optional Filtering: If they ask for only INCOME or EXPENSE
#     if transaction_type:
#         query = query.filter(models.Record.type == transaction_type.upper())

#     # Execute the query with pagination (skip and limit)
#     records = query.offset(skip).limit(limit).all()
#     return records

# # --- DASHBOARD SUMMARY ROUTE ---


# # 2. Admins AND Viewers can see the dashboard
# @app.get("/dashboard")
# def get_dashboard_summary(
#     db: Session = Depends(get_db),
#     current_user: models.User = Depends(require_role(
#         ["ADMIN", "VIEWER"]))  # <-- SECURITY CHECK
# ):
#     total_income = db.query(func.sum(models.Record.amount)).filter(
#         models.Record.user_id == current_user.id,
#         models.Record.type == "INCOME"
#     ).scalar() or 0.0

#     total_expense = db.query(func.sum(models.Record.amount)).filter(
#         models.Record.user_id == current_user.id,
#         models.Record.type == "EXPENSE"
#     ).scalar() or 0.0

#     net_balance = total_income - total_expense

#     recent_activity = db.query(models.Record).filter(
#         models.Record.user_id == current_user.id
#     ).order_by(models.Record.date.desc()).limit(5).all()

#     return {
#         "total_income": total_income,
#         "total_expense": total_expense,
#         "net_balance": net_balance,
#         "recent_activity": recent_activity
#     }

# --- 1. ACCESS CONTROL (Requirement 4) ---
def require_role(allowed_roles: list[str]):
    def role_checker(x_user_id: int = Header(...), db: Session = Depends(get_db)):
        user = db.query(models.User).filter(
            models.User.id == x_user_id).first()
        if not user:
            raise HTTPException(status_code=401, detail="Auth Failed")
        if not user.is_active:
            raise HTTPException(status_code=403, detail="User Inactive")
        if user.role not in allowed_roles:
            raise HTTPException(status_code=403, detail="Forbidden")
        return user
    return role_checker

# --- 2. USER MANAGEMENT (Requirement 1) ---


@app.post("/users", response_model=schemas.UserResponse)
def create_user(user: schemas.UserCreate, db: Session = Depends(get_db)):
    db_user = db.query(models.User).filter(
        models.User.email == user.email).first()
    if db_user:
        raise HTTPException(status_code=400, detail="Exists")
    new_user = models.User(
        email=user.email, password=user.password, role=user.role)
    db.add(new_user)
    db.commit()
    db.refresh(new_user)
    return new_user


@app.patch("/users/{user_id}/status")
def toggle_user_status(user_id: int, is_active: bool, db: Session = Depends(get_db), current_user: models.User = Depends(require_role(["ADMIN"]))):
    user = db.query(models.User).filter(models.User.id == user_id).first()
    user.is_active = is_active
    db.commit()
    return {"msg": "Updated"}

# --- 3. RECORD MANAGEMENT (Requirement 2) ---

# ADMIN can create for ANYONE. ANALYST can create for THEMSELVES.


@app.post("/records/{target_user_id}", response_model=schemas.RecordResponse)
def create_record(target_user_id: int, record: schemas.RecordCreate, db: Session = Depends(get_db), current_user: models.User = Depends(require_role(["ADMIN", "ANALYST"]))):
    if current_user.role == "ANALYST" and current_user.id != target_user_id:
        raise HTTPException(
            status_code=403, detail="Analysts can only fill their own")
    new_rec = models.Record(**record.dict(), user_id=target_user_id)
    db.add(new_rec)
    db.commit()
    db.refresh(new_rec)
    return new_rec


@app.get("/records", response_model=list[schemas.RecordResponse])
def get_records(type: str = None, db: Session = Depends(get_db), current_user: models.User = Depends(require_role(["ADMIN", "ANALYST", "VIEWER"]))):
    query = db.query(models.Record)
    if current_user.role != "ADMIN":
        query = query.filter(models.Record.user_id == current_user.id)
    if type:
        query = query.filter(models.Record.type == type.upper())
    return query.all()


@app.put("/records/{record_id}", response_model=schemas.RecordResponse)
def update_record(record_id: int, update: schemas.RecordUpdate, db: Session = Depends(get_db), current_user: models.User = Depends(require_role(["ADMIN"]))):
    db_rec = db.query(models.Record).filter(
        models.Record.id == record_id).first()
    for key, value in update.dict(exclude_unset=True).items():
        setattr(db_rec, key, value)
    db.commit()
    return db_rec


@app.delete("/records/{record_id}")
def delete_record(record_id: int, db: Session = Depends(get_db), current_user: models.User = Depends(require_role(["ADMIN"]))):
    db_rec = db.query(models.Record).filter(
        models.Record.id == record_id).first()
    db.delete(db_rec)
    db.commit()
    return {"msg": "Deleted"}

# --- 4. DASHBOARD (Requirement 3) ---


@app.get("/dashboard/{user_id}")
def get_dashboard(
    user_id: int,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(require_role(
        ["ADMIN", "ANALYST", "VIEWER"]))  # <--- ADDED VIEWER
):
    # LOGIC CHECK:
    # 1. If you are an ADMIN, you can see ANY user_id dashboard.
    # 2. If you are an ANALYST or VIEWER, you can ONLY see your own user_id.

    if current_user.role != "ADMIN" and current_user.id != user_id:
        raise HTTPException(
            status_code=403,
            detail="You are only allowed to view your own dashboard data."
        )

    # --- THE MATH (Stays the same) ---
    income = db.query(func.sum(models.Record.amount)).filter(
        models.Record.user_id == user_id, models.Record.type == "INCOME").scalar() or 0
    expense = db.query(func.sum(models.Record.amount)).filter(
        models.Record.user_id == user_id, models.Record.type == "EXPENSE").scalar() or 0
    cats = db.query(models.Record.category, func.sum(models.Record.amount)).filter(
        models.Record.user_id == user_id).group_by(models.Record.category).all()
    recent = db.query(models.Record).filter(models.Record.user_id == user_id).order_by(
        models.Record.date.desc()).limit(5).all()

    return {
        "total_income": income,
        "total_expense": expense,
        "net_balance": income - expense,
        "category_totals": [{"category": c, "total": t} for c, t in cats],
        "recent_activity": recent
    }
